all: build

build: assignment11.o daemonize.o
	gcc -o assignment11 assignment11.o daemonize.o

assgt: assignment11.c
	gcc assignment11.c -o assignment11.o -c

daemon: daemonize.c
	gcc daemonize.c -o daemonize.o -c
